// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pttthnltclfbxehenalj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0dHRobmx0Y2xmYnhlaGVuYWxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjY2OTQsImV4cCI6MjA3NDE0MjY5NH0.RWi_nRYF0NNAkiHqj9JHbQTyEG-VA5M9dN7Gh3DALCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});